import 'package:flutter/material.dart';

class AppColors {
  AppColors._();

  static const Color primary = Color(0xFF22A699);
  static const Color secondary = Color(0xFF5CCFC4);
  static const Color tertiary = Color(0xFF1B8E82);
  static const Color appBarTitle = Color(0xFF0B7267);
  static const Color appBarSubtitle = Color(0xFF58615F);
  static const Color appBarBackground = Color(0xFFFFFFFF);
  static const Color appBarDivider = Color(0xFFE5E8E7);
  static const Color background = Color(0xFFF5FBF8);
  static const Color surface = Color(0xFFF5FBF8);
  static const Color surfaceLowest = Color(0xFFFFFFFF);
  static const Color surfaceContainer = Color(0xFFEFF5F2);
  static const Color surfaceAlt = Color(0xFFF0F6F5);
  static const Color surfaceSoft = Color(0xFFECF8F4);
  static const Color surfaceBright = Color(0xFFF9FCFB);
  static const Color surfaceTint = Color(0xFFC9EDE7);
  static const Color surfaceTintStrong = Color(0xFF94D7CC);
  static const Color onPrimary = Color(0xFFFFFFFF);
  static const Color textPrimary = Color(0xFF191C1B);
  static const Color textSecondary = Color(0xFF3F4946);
  static const Color textMuted = Color(0xFF9AA8A3);
  static const Color onSurface = Color(0xFF191C1B);
  static const Color onSurfaceVariant = Color(0xFF3F4946);
  static const Color outline = Color(0xFF6F7976);
  static const Color outlineSoft = Color(0xFFE8F7F5);
  static const Color textOnMuted = Color(0xFF374B49);
  static const Color textDisabled = Color(0xFFB8C4C2);
  static const Color textCalendar = Color(0xFF7E8D8B);
  static const Color avatarBorder = Color(0xFF17A89B);
  static const Color avatarBackground = Color(0xFFDAF5F1);
  static const Color avatarOuter = Color(0xFF1AA79A);
  static const Color avatarInner = Color(0xFF355E5E);
  static const Color avatarSurface = Color(0xFFE6EEEE);
  static const Color avatarIcon = Color(0xFF0B7267);
  static const Color avatarEditBackground = Color(0xFF0B7267);
  static const Color avatarEditIcon = Color(0xFFFFFFFF);
  static const Color success = Color(0xFF4CAF50);
  static const Color warning = Color(0xFFFFB300);
  static const Color error = Color(0xFFF44336);
  static const Color shadowLight = Color(0x0D000000);
  static const Color transparent = Color(0x00000000);
  static const Color googleBlue = Color(0xFF4285F4);
  static const Color googleRed = Color(0xFFEA4335);
  static const Color googleYellow = Color(0xFFFBBC05);
  static const Color googleGreen = Color(0xFF34A853);
}
